language: node_js

branches:
  only:
    - master
    - /^greenkeeper/.*$/

cache: yarn

node_js:
  - '8'
  - '4'
  - '10'

before_install: yarn global add greenkeeper-lockfile@1

before_script: greenkeeper-lockfile-update

script: yarn run test

after_script: greenkeeper-lockfile-upload

after_success:
  - yarn global add travis-deploy-once
  - travis-deploy-once "yarn global add semantic-release@12 && semantic-release"
