language: node_js
branches:
  only:
    - master
cache:
  directories:
    - node_modules
node_js:
  - '6'
before_script:
  - npm prune
script: npm run test
after_success:
  - npm run semantic-release
