language: node_js

branches:
  only:
    - master
    - /^greenkeeper/.*$/

cache: yarn

node_js:
  - '6'

before_install: yarn global add greenkeeper-lockfile@1

before_script: greenkeeper-lockfile-update

script: yarn run test

after_script: greenkeeper-lockfile-upload

after_success:
  - yarn run semantic-release
